/**
 * Database type definitions for Supabase
 *
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --project-id <project-id> > src/types/database.ts
 *
 * For now, we define the expected schema manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string | null;
          display_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          is_anonymous_default: boolean;
          hobby_tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username?: string | null;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          is_anonymous_default?: boolean;
          hobby_tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string | null;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          is_anonymous_default?: boolean;
          hobby_tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      posts: {
        Row: {
          id: string;
          user_id: string;
          content: string;
          is_anonymous: boolean;
          images: string[];
          hobby_tags: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          content: string;
          is_anonymous?: boolean;
          images?: string[];
          hobby_tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          content?: string;
          is_anonymous?: boolean;
          images?: string[];
          hobby_tags?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          content: string;
          is_anonymous: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          content: string;
          is_anonymous?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          content?: string;
          is_anonymous?: boolean;
          created_at?: string;
        };
      };
      reactions: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          type: 'like' | 'empathy' | 'relatable' | 'support';
          created_at: string;
        };
        Insert: {
          id?: string;
          post_id: string;
          user_id: string;
          type: 'like' | 'empathy' | 'relatable' | 'support';
          created_at?: string;
        };
        Update: {
          id?: string;
          post_id?: string;
          user_id?: string;
          type?: 'like' | 'empathy' | 'relatable' | 'support';
          created_at?: string;
        };
      };
      communities: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          is_private: boolean;
          hobby_tags: string[];
          owner_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          is_private?: boolean;
          hobby_tags?: string[];
          owner_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          is_private?: boolean;
          hobby_tags?: string[];
          owner_id?: string;
          created_at?: string;
        };
      };
      community_members: {
        Row: {
          community_id: string;
          user_id: string;
          role: 'owner' | 'moderator' | 'member';
          joined_at: string;
        };
        Insert: {
          community_id: string;
          user_id: string;
          role?: 'owner' | 'moderator' | 'member';
          joined_at?: string;
        };
        Update: {
          community_id?: string;
          user_id?: string;
          role?: 'owner' | 'moderator' | 'member';
          joined_at?: string;
        };
      };
      follows: {
        Row: {
          follower_id: string;
          following_id: string;
          created_at: string;
        };
        Insert: {
          follower_id: string;
          following_id: string;
          created_at?: string;
        };
        Update: {
          follower_id?: string;
          following_id?: string;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          event_type: 'onsen' | 'drive' | 'cafe' | 'other' | null;
          location: string | null;
          event_date: string | null;
          max_participants: number | null;
          community_id: string | null;
          organizer_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          event_type?: 'onsen' | 'drive' | 'cafe' | 'other' | null;
          location?: string | null;
          event_date?: string | null;
          max_participants?: number | null;
          community_id?: string | null;
          organizer_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          event_type?: 'onsen' | 'drive' | 'cafe' | 'other' | null;
          location?: string | null;
          event_date?: string | null;
          max_participants?: number | null;
          community_id?: string | null;
          organizer_id?: string;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      reaction_type: 'like' | 'empathy' | 'relatable' | 'support';
      member_role: 'owner' | 'moderator' | 'member';
      event_type: 'onsen' | 'drive' | 'cafe' | 'other';
    };
  };
};

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> =
  Database['public']['Enums'][T];

// Convenience types
export type Profile = Tables<'profiles'>;
export type Post = Tables<'posts'>;
export type Comment = Tables<'comments'>;
export type Reaction = Tables<'reactions'>;
export type Community = Tables<'communities'>;
export type CommunityMember = Tables<'community_members'>;
export type Follow = Tables<'follows'>;
export type Event = Tables<'events'>;
